const mongoose=require("mongoose");

const projectSchema= new mongoose.Schema({
    title:{
        type:string,
    },
    domain:{
        type: mongoose.Schema.ObjectId,
        ref:"Domain",
    },
    description:{
        type:string,
    },
    startDate:{
        type:Date,
    },
    endDate:{
        type:Date,
    },
    ratings:{
        type:Number,
        default:0
    },
    numOfReviews:{
        type:Number,
        default:0
    },
    reviews:[
        {
            userId:{
                type:mongoose.Schema.ObjectId,
                ref:"User",
                required:true,
            },
            name:{
                type:String,
                required:true,
            },
            rating:{
                type:Number,
                required:true,
            },
            comment:{
                type:String,
                
            }
        }
    ],
    mentor:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
    },
    organization:{
        type:mongoose.Schema.ObjectId,
        ref:"Organization",
    },
    menteesRequired:{
        type:Number,
        default:0
    },
    menteesApplication:[
        {
            userId:{
                type:mongoose.Schema.ObjectId,
                ref:"User",
            },
            name:{
                type:String,
            },
            status:{
                type:String,
            }
        }
    ],
    menteesApproved:[
        {
            userId:{
                type:mongoose.Schema.ObjectId,
                ref:"User",
            },
            name:{
                type:String,
            },
        }
    ],
    tasks:[
        {
            id:{
                type:Number
            },
            title:{
                type:string,
            },
            description:{
                type:string,
            },
            priority:{
                type:string,
            },
            dueDate:{
                type:Date
            },
            taskStatus:{
                type:String
            },
            menteesAssigned:[
                {
                    userId:{
                        type:mongoose.Schema.ObjectId,
                        ref:"User",
                    },
                    name:{
                        type:String,
                    },
                }
            ],
            mentorProvidedDocuments:[
                {
                    public_id:{
                        type:string,
                        required:true,
                    },
                    url:{
                        type:string,
                        required:true,
                    }
                },
            ],
            menteeUploadedDocuments:[
                {
                    public_id:{
                        type:string,
                        required:true,
                    },
                    url:{
                        type:string,
                        required:true,
                    },
                    uploadDate:{
                        type:Date
                    }
                },
            ],
        }
    ],
    links:[
        {
            linkType:{
                type:String
            },
            linkUrl:{
                type:String
            }
        }
    ]
})

module.exports=mongoose.model("Project",projectSchema);